package pojos;
// Generated Jun 8, 2018 5:17:00 PM by Hibernate Tools 4.3.1



/**
 * Establishments generated by hbm2java
 */
public class Establishments  implements java.io.Serializable {


     private int id;
     private String name;

    public Establishments() {
    }

	
    public Establishments(int id) {
        this.id = id;
    }
    public Establishments(int id, String name) {
       this.id = id;
       this.name = name;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


